// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chung.Models;

namespace chung.Migrations
{
    [DbContext(typeof(SVienContext))]
    [Migration("20190729013013_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("chung.Models.Lop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("chung.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("IdLop")
                        .HasColumnName("Id_Lop");

                    b.HasKey("Id");

                    b.HasIndex("IdLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("chung.Models.SinhVien", b =>
                {
                    b.HasOne("chung.Models.Lop", "IdLopNavigation")
                        .WithMany("SinhVien")
                        .HasForeignKey("IdLop")
                        .HasConstraintName("FK__SinhVien__Id_Lop__38996AB5");
                });
#pragma warning restore 612, 618
        }
    }
}
